from __future__ import annotations

import base64
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
SOURCE_DIR = ROOT / "\u652f\u6301\u4f5c\u8005"
OUTPUT = ROOT / "ui" / "embedded_assets.py"
ASSETS = {
    "RED_PACKET_JPG": "\u7ea2\u5305\u7801.jpg",
    "SUPPORT_QR_PNG": "\u6536\u6b3e\u7801.png",
}


def main() -> None:
    lines = [
        "from __future__ import annotations",
        "",
        "# Generated by scripts/generate_embedded_assets.py",
        "",
    ]
    for variable_name, filename in ASSETS.items():
        path = SOURCE_DIR / filename
        encoded = base64.b64encode(path.read_bytes()).decode("ascii")
        lines.append(f"{variable_name} = (")
        lines.append(f"    '{encoded}'")
        lines.append(")")
        lines.append("")
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
